Repository Kernel360/hackerthon4-BABPOOL-BE, pull requests merged in 2025-03, with the labels that each got.

#9 Feat/8 common response update
  src/main/java/org/example/hana/global/common/CommonErrorResponse.java
  src/main/java/org/example/hana/global/common/CommonResponse.java
  src/main/java/org/example/hana/global/exception/CustomException.java
  src/main/java/org/example/hana/global/exception/ErrorCode.java
  src/main/java/org/example/hana/global/exception/GlobalExceptionHandler.java
Labels: 💻 BE, ✨ Feature

#11 feat: 모임 공고 CRUD 기능 추가
  src/main/java/org/example/hana/recruitment/controller/RecruitmentPostController.java
  src/main/java/org/example/hana/recruitment/db/RecruitmentPostRepository.java
  src/main/java/org/example/hana/recruitment/entity/RecruitmentPost.java
  src/main/java/org/example/hana/recruitment/model/RecruitmentPostListResponse.java
  src/main/java/org/example/hana/recruitment/model/RecruitmentPostRequest.java
  src/main/java/org/example/hana/recruitment/service/RecruitmentPostService.java
Labels: 💻 BE, ✨ Feature

#19 Feat: 16 chatting
  .gradle/8.12.1/checksums/checksums.lock
  .gradle/8.12.1/checksums/md5-checksums.bin
  .gradle/8.12.1/checksums/sha1-checksums.bin
  build.gradle
  out/production/classes/org/example/hana/chatting/WebSocketConfig.class
  out/production/classes/org/example/hana/chatting/controller/ChatMessageController.class
  out/production/classes/org/example/hana/chatting/controller/dto/ChatMessageRequestDto.class
  out/production/classes/org/example/hana/chatting/controller/dto/ChatMessageResponseDto$ChatMessageResponseDtoBuilder.class
  out/production/classes/org/example/hana/chatting/controller/dto/ChatMessageResponseDto.class
  out/production/classes/org/example/hana/chatting/entity/ChatMessage$ChatMessageBuilder.class
  out/production/classes/org/example/hana/chatting/entity/ChatMessage.class
  out/production/classes/org/example/hana/chatting/repository/ChatMessageRepository.class
  out/production/classes/org/example/hana/global/config/SecurityConfig.class
  out/production/classes/org/example/hana/global/jwt/JwtAccessDeniedHandler.class
  out/production/classes/org/example/hana/global/jwt/JwtAuthenticationEntryPoint.class
  out/production/classes/org/example/hana/global/jwt/JwtFilter.class
  out/production/classes/org/example/hana/global/jwt/JwtSecurityConfig.class
  out/production/classes/org/example/hana/global/jwt/TokenProvider.class
  out/production/classes/org/example/hana/recruitment/controller/RecruitmentCommentController.class
  out/production/classes/org/example/hana/recruitment/controller/RecruitmentPostController.class
  out/production/classes/org/example/hana/recruitment/db/ApplicationRepository.class
  out/production/classes/org/example/hana/recruitment/db/RecruitmentCommentRepository.class
  out/production/classes/org/example/hana/recruitment/db/RecruitmentPostRepository.class
  out/production/classes/org/example/hana/recruitment/entity/Application$ApplicationBuilder.class
  out/production/classes/org/example/hana/recruitment/entity/Application.class
  out/production/classes/org/example/hana/recruitment/model/RecruitmentCommentRequest.class
  out/production/classes/org/example/hana/recruitment/model/RecruitmentCommentResponse.class
  out/production/classes/org/example/hana/recruitment/model/RecruitmentPostListResponse.class
  out/production/classes/org/example/hana/recruitment/model/RecruitmentPostRequest.class
  out/production/classes/org/example/hana/recruitment/model/RecruitmentPostResponse.class
  out/production/classes/org/example/hana/recruitment/service/ApplicationService.class
  out/production/classes/org/example/hana/recruitment/service/RecruitmentCommentService.class
  out/production/classes/org/example/hana/recruitment/service/RecruitmentPostService.class
  out/production/classes/org/example/hana/review/controller/ReviewPostController.class
  out/production/classes/org/example/hana/review/service/ReviewPostService.class
  out/production/classes/org/example/hana/user/controller/UserController.class
  out/production/classes/org/example/hana/user/dto/TokenDto$TokenDtoBuilder.class
  out/production/classes/org/example/hana/user/dto/TokenDto.class
  out/production/classes/org/example/hana/user/dto/TokenRequestDto.class
  out/production/classes/org/example/hana/user/dto/UserRequestDto.class
  out/production/classes/org/example/hana/user/dto/UserResponseDto$UserResponseDtoBuilder.class
  out/production/classes/org/example/hana/user/dto/UserResponseDto.class
  out/production/classes/org/example/hana/user/entity/RefreshToken$RefreshTokenBuilder.class
  out/production/classes/org/example/hana/user/entity/RefreshToken.class
  out/production/classes/org/example/hana/user/repository/RefreshTokenRepository.class
  out/production/classes/org/example/hana/user/repository/UserRepository.class
  out/production/classes/org/example/hana/user/service/CustomUserDetailService.class
  out/production/classes/org/example/hana/user/service/UserService.class
  src/main/java/org/example/hana/chatting/WebSocketConfig.java
  src/main/java/org/example/hana/chatting/controller/ChatMessageController.java
  src/main/java/org/example/hana/chatting/controller/dto/ChatMessageRequestDto.java
  src/main/java/org/example/hana/chatting/controller/dto/ChatMessageResponseDto.java
  src/main/java/org/example/hana/chatting/entity/ChatMessage.java
  src/main/java/org/example/hana/chatting/repository/ChatMessageRepository.java
  src/main/java/org/example/hana/review/controller/ReviewPostController.java
  src/main/java/org/example/hana/review/service/ReviewPostService.java
Labels: 📬 API, 💻 BE

#21 Fix: UserController, UserService 수정
  src/main/java/org/example/hana/user/controller/UserController.java
  src/main/java/org/example/hana/user/service/UserService.java
Labels: 💻 BE, 🐞 Fix
